### ISSUE TITLE
Generated typescript doesn't use '?' for null types

### ISSUE THREAD

**Issue by Sethuraman** [ntrrgc/ts-generator#25]
I was wondering why the generator generates :

```
interface Folio {
    addressLine1: string;
    addressLine2: string | null;
}
```
instead of 
```
interface Folio {
    addressLine1: string;
    addressLine2?: string;
}
```

**Comment by brezinajn** [comment]
`addressLine2?: string` denotes optional field whether `addressLine2: string | null;` denotes required nullable field and that is exactly what your Kotlin class says :). Kotlin does not really have a concept of optional fields.

**Comment by Sethuraman** [comment]
Thanks @brezinajn . New to typescript.  I understand
